Metatavu/metamind-api

- src/main/java/fi/metatavu/metamind/server/rest/AccessControlAllowOriginFilter.java
> Added allow origin filter

- pom.xml
- src/main/java/fi/metatavu/metamind/persistence/dao/SessionDAO.java
- src/main/java/fi/metatavu/metamind/server/rest/MessageApiImpl.java
- src/main/java/fi/metatavu/metamind/sessions/SessionController.java
> Bot session state is now persisted after each message

- src/main/java/fi/metatavu/metamind/persistence/dao/QuickResponseDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/QuickResponse.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/MessageTranslator.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
> Renamed option to quickResponseText

- src/main/java/fi/metatavu/metamind/bot/config/TokenizationConfig.java
- src/main/java/fi/metatavu/metamind/bot/functions/AbstractMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/functions/CapitalizeFullyMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/tokenizer/SimpleTokenizer.java
- src/main/java/fi/metatavu/metamind/bot/tokenizer/TemplateTokenizer.java
- src/main/java/fi/metatavu/metamind/server/rest/SystemApi.java
> Added bot function for capitalizing words

- src/main/java/fi/metatavu/metamind/server/rest/SystemRESTService.java
> Added system ping endpoint

- src/main/java/fi/metatavu/metamind/bot/functions/AbstractMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/functions/RoundMetaBotFunction.java
> Added function for rounding numbers

- src/main/java/fi/metatavu/metamind/bot/MetamindBotConfiguration.java
- src/main/java/fi/metatavu/metamind/bot/config/StoryConfig.java
> Feature #28 confused knot

- pom.xml
- src/main/java/fi/metatavu/metamind/bot/functions/AbstractFreemarkerMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/functions/EmailMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/server/rest/MessageApiImpl.java
- src/main/webapp/WEB-INF/jboss-deployment-structure.xml
> Hotfix #30 session attributes

- src/main/java/fi/metatavu/metamind/bot/MetamindBot.java
- src/main/java/fi/metatavu/metamind/bot/MetamindBotConfiguration.java
- src/main/java/fi/metatavu/metamind/bot/config/StoryConfig.java
- src/main/java/fi/metatavu/metamind/bot/functions/GoToCheckPointMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/functions/SaveCheckpointMetaBotFunction.java
> Added support for global intents

- src/main/java/fi/metatavu/metamind/persistence/models/FreemarkerTemplate.java
- src/main/java/fi/metatavu/metamind/persistence/models/IntentModel.java
- src/main/java/fi/metatavu/metamind/persistence/models/Session.java
- src/main/java/fi/metatavu/metamind/persistence/models/SlotModel.java
- src/main/java/fi/metatavu/metamind/persistence/models/Story.java
> Added cache annotations into frequently used entities

- src/main/java/fi/metatavu/metamind/bot/functions/AbstractMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/functions/GetStoryGlobalVariableBotFunction.java
- src/main/java/fi/metatavu/metamind/persistence/dao/StoryGlobalVariableDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/StoryGlobalVariable.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
> Feature #40 global story variables

- src/main/java/fi/metatavu/metamind/bot/BotController.java
- src/main/java/fi/metatavu/metamind/bot/MetamindBotConfiguration.java
- src/main/java/fi/metatavu/metamind/bot/OpenNLPIntentMatcher.java
- src/main/java/fi/metatavu/metamind/bot/OpenNLPSlotMatcher.java
- src/main/java/fi/metatavu/metamind/server/rest/SystemApi.java
- src/main/java/fi/metatavu/metamind/settings/SystemConsts.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
> Changed models to be loaded from database

- src/main/java/fi/metatavu/metamind/persistence/dao/ClientDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/AccessType.java
- src/main/java/fi/metatavu/metamind/persistence/models/Client.java
- src/main/java/fi/metatavu/metamind/security/SecurityController.java
- src/main/java/fi/metatavu/metamind/server/rest/security/ClientContainer.java
- src/main/java/fi/metatavu/metamind/server/rest/security/RestSecurityWhitelist.java
- src/main/java/fi/metatavu/metamind/server/rest/security/SecurityFilter.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
- src/main/resources/security-whitelist.properties
> Added support for detecting clients

- src/main/java/fi/metatavu/metamind/bot/functions/BailOutMetabotFuction.java
> Added bail_out bot function

- src/main/java/fi/metatavu/metamind/bot/tokenizer/TemplateTokenizer.java
> Match also partially to strings when using strip whitespace tokenizer

- src/main/java/fi/metatavu/metamind/bot/functions/DateFromNowMetaBotFunction.java
> Added date from now metabot function

- src/main/java/fi/metatavu/metamind/bot/tokenizer/SimpleTokenizer.java
> Support also comma as decimal separator

- pom.xml
- src/main/java/fi/metatavu/metamind/bot/MetamindBotConfiguration.java
- src/main/java/fi/metatavu/metamind/bot/slots/LocalizedNumberSlot.java
- src/main/java/fi/metatavu/metamind/bot/slots/utils/FinnishStringToNumberUtils.java
- src/main/java/fi/metatavu/metamind/bot/slots/utils/FinnishWordToNumberResult.java
- src/test/java/fi/metatavu/metamind/bot/slots/LocalizedNumberSlotTest.java
- src/test/java/fi/metatavu/metamind/slot/models/NumberSlotTestModels.java
- src/test/java/fi/metatavu/metamind/slot/models/NumberSlotTestsModel.java
- src/test/resources/fi/metatavu/metamind/bot/slots/number-slot-tests.json
- travis.sh
> Added support for finnish number slots

- src/main/java/fi/metatavu/metamind/bot/BotController.java
- src/main/java/fi/metatavu/metamind/bot/MetamindBotConfiguration.java
- src/main/java/fi/metatavu/metamind/bot/MultiIntentMatcher.java
- src/main/java/fi/metatavu/metamind/bot/config/StoryConfig.java
> Feature #59 multiple binary files

- .gitignore
- pom.xml
- src/main/java/fi/metatavu/metamind/bot/BotController.java
- src/main/java/fi/metatavu/metamind/bot/IgnoreCaseTokenizerWrapper.java
- src/main/java/fi/metatavu/metamind/bot/MetamindBotConfiguration.java
- src/main/java/fi/metatavu/metamind/bot/config/MachineLearningConfig.java
- src/main/java/fi/metatavu/metamind/bot/functions/BeerApiBeerInfoMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/functions/BeerApiListBeersMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/functions/DetectLanguageMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/functions/GetRandomSequencyItemMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/bot/utils/TextLanguageDetector.java
- src/main/java/fi/metatavu/metamind/server/rest/AccessControlAllowOriginFilter.java
> Feature #66 beer search

- src/main/java/fi/metatavu/metamind/bot/functions/BeerApiListBeersMetaBotFunction.java
> Fixed beer querying parameters

- src/main/java/fi/metatavu/metamind/bot/MetamindBotConfiguration.java
- src/main/java/fi/metatavu/metamind/bot/config/StoryConfig.java
> Added support for configuring default responses

- pom.xml
- src/main/java/fi/metatavu/metamind/bot/functions/RunScriptMetaBotFunction.java
- src/main/java/fi/metatavu/metamind/persistence/dao/ScriptDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/Script.java
- src/main/java/fi/metatavu/metamind/polyglot/ReadyState.java
- src/main/java/fi/metatavu/metamind/polyglot/ResponseType.java
- src/main/java/fi/metatavu/metamind/polyglot/XMLHttpRequest.java
- src/main/java/fi/metatavu/metamind/scripts/ScriptController.java
- src/main/java/fi/metatavu/metamind/server/rest/MessageApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/ScriptsApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/SessionApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/ScriptTranslator.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
> Feature 80 scripting api

- pom.xml
- src/main/java/fi/metatavu/metamind/persistence/dao/AbstractDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/Client.java
- src/main/java/fi/metatavu/metamind/persistence/models/FreemarkerTemplate.java
- src/main/java/fi/metatavu/metamind/persistence/models/IntentModel.java
- src/main/java/fi/metatavu/metamind/persistence/models/Message.java
- src/main/java/fi/metatavu/metamind/persistence/models/QuickResponse.java
- src/main/java/fi/metatavu/metamind/persistence/models/Script.java
- src/main/java/fi/metatavu/metamind/persistence/models/Session.java
- src/main/java/fi/metatavu/metamind/persistence/models/SlotModel.java
- src/main/java/fi/metatavu/metamind/persistence/models/Story.java
- src/main/java/fi/metatavu/metamind/persistence/models/StoryGlobalVariable.java
- src/main/java/fi/metatavu/metamind/persistence/models/SystemSetting.java
> Bumped Wildfly to 16

- pom.xml
- src/main/java/fi/metatavu/metamind/persistence/models/TrainingMaterial.java
- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
> Feature 90 redirect intents

- pom.xml
- src/main/java/fi/metatavu/metamind/nlp/TrainingMaterialController.java
- src/main/java/fi/metatavu/metamind/persistence/models/TrainingMaterial.java
- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
> Hotfix 92 intent training material update

- pom.xml
- src/main/java/fi/metatavu/metamind/bot/BotController.java
- src/main/java/fi/metatavu/metamind/bot/match/AnyIntentMatcher.java
- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
> Added support for default intents

- pom.xml
- src/main/java/fi/metatavu/metamind/bot/BotController.java
- src/main/java/fi/metatavu/metamind/bot/match/OpenNlpDoccatIntentMatcher.java
- src/main/java/fi/metatavu/metamind/bot/match/RegexIntentMatcher.java
- src/main/java/fi/metatavu/metamind/bot/tokenization/Tokenizer.java
- src/main/java/fi/metatavu/metamind/bot/tokenization/TokenizerFactory.java
- src/main/java/fi/metatavu/metamind/bot/tokenization/UntokenizedTokenizer.java
- src/main/java/fi/metatavu/metamind/bot/tokenization/UntokenizerdTokenizer.java
- src/main/java/fi/metatavu/metamind/bot/tokenization/WhitespaceTokenizer.java
- src/main/java/fi/metatavu/metamind/bot/variables/AbstractOpenNlpVariableFinder.java
- src/main/java/fi/metatavu/metamind/bot/variables/OpenNlpNerVariableFinder.java
- src/main/java/fi/metatavu/metamind/bot/variables/OpenNlpRegExVariableFinder.java
- src/main/java/fi/metatavu/metamind/persistence/dao/KnotDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/Knot.java
- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/KnotTranslator.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
> Added support for changing knot tokenizers

- src/main/java/fi/metatavu/metamind/persistence/dao/IntentTrainingMaterialDAO.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
> Fixed foreign key constraint error when deleting intents

- src/main/java/fi/metatavu/metamind/messages/MessageController.java
- src/main/java/fi/metatavu/metamind/persistence/dao/MessageDAO.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
> Fixed issue #102

- pom.xml
- src/main/java/fi/metatavu/metamind/persistence/dao/IntentDAO.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/StoryTranslator.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
> Added support for global quick replies

- pom.xml
- src/main/java/fi/metatavu/metamind/nlp/TrainingMaterialController.java
- src/main/java/fi/metatavu/metamind/persistence/dao/IntentDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/Intent.java
- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/IntentTranslator.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
> Added support for quick response order

- .gitignore
- pom.xml
- scripts/export-keycloak-config.sh
- scripts/kc-setup-for-tests.json
- scripts/keycloak-version.sh
- scripts/setup-db-mysql.sql
- scripts/setup-db.sql
- scripts/start-keycloak.sh
- scripts/stop-keycloak.sh
- src/test/java/fi/metatavu/metamind/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/metamind/test/functional/StoryTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/AbstractTestBuilderResource.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/CloseableResource.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/TestBuilder.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/TestBuilderResource.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/AccessTokenProvider.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/DefaultAccessTokenProvider.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/InvalidAccessTokenProvider.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/NullAccessTokenProvider.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/TestBuilderAuthentication.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/impl/StoryTestBuilderResource.java
- src/test/java/fi/metatavu/metamind/test/functional/settings/TestSettings.java
> Feature 110 functional tests

- .gitignore
- .travis.yml
- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/test/java/fi/metatavu/metamind/test/functional/StoryTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/TestBuilder.java
- travis-before-script.sh
- travis.sh
> Feature 112 crudtestsforstories

- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/KnotTranslator.java
- src/test/java/fi/metatavu/metamind/test/functional/KnotTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/AbstractTestBuilderResource.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/TestBuilder.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/impl/KnotTestBuilderResource.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/impl/StoryTestBuilderResource.java
> Feature 113 crudtestsforknots

- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/test/java/fi/metatavu/metamind/test/functional/IntentTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/impl/IntentTestBuilderResource.java
> Feature 114 crudtestsforintents

- pom.xml
- src/main/java/fi/metatavu/metamind/persistence/dao/StoryDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/Story.java
- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/StoryTranslator.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
- src/test/java/fi/metatavu/metamind/test/functional/IntentTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/KnotTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/StoryTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/impl/StoryTestBuilderResource.java
> Feature 115 testsforstoryhints

- src/test/java/fi/metatavu/metamind/test/functional/TrainingMaterialTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/impl/IntentTrainingMaterialTestBuilderResource.java
> Feature 117 crudtestsfortrainingmaterial

- pom.xml
- src/main/java/fi/metatavu/metamind/nlp/TrainingMaterialController.java
- src/main/java/fi/metatavu/metamind/persistence/dao/TrainingMaterialDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/TrainingMaterial.java
- src/main/java/fi/metatavu/metamind/server/rest/TrainingMaterialsApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/TrainingMaterialTranslator.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
- src/test/java/fi/metatavu/metamind/test/functional/TrainingMaterialTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/impl/IntentTrainingMaterialTestBuilderResource.java
> Feature 135 story wide training material

- pom.xml
- src/main/java/fi/metatavu/metamind/persistence/dao/KnotDAO.java
- src/main/java/fi/metatavu/metamind/persistence/models/Knot.java
- src/main/java/fi/metatavu/metamind/server/rest/StoriesApiImpl.java
- src/main/java/fi/metatavu/metamind/server/rest/translation/KnotTranslator.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
- src/main/resources/fi/metatavu/metamind/changelog.xml
- src/test/java/fi/metatavu/metamind/test/functional/IntentTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/KnotTestsIT.java
- src/test/java/fi/metatavu/metamind/test/functional/builder/impl/KnotTestBuilderResource.java
> feature-136-storeknotcoordinates

- src/main/java/fi/metatavu/metamind/bot/script/BotStoryScriptBinding.java
- src/main/java/fi/metatavu/metamind/persistence/dao/KnotDAO.java
- src/main/java/fi/metatavu/metamind/story/StoryController.java
> Added support for searching knots by name via scripting API
